### ISSUE TITLE
Convert CI Pipeline to Github Actions

### ISSUE THREAD

**Issue by FlorianRohm** [TNG/gs-rs#2]
We should think about converting the CI pipeline to github actions for this project as it has a better integration to github (obviously).

Link to rust quickstart template for this repo: https://github.com/TNG/gs-rs/new/master?filename=.github%2Fworkflows%2Frust.yml&workflow_template=rust

**Comment by maxhbr** [comment]
I see commits that reference this issue, is that fixed?
